version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
  redis:
    image: "redis:7.2-bookworm"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
